### ISSUE TITLE
npm run start运行出问题

### ISSUE THREAD

**Issue by wangwenyu0805** [maoxiaoquan/kite-admin#2]
其他的步骤都做完了，前端也启动了，后台管理部分，我先npm install，再npm run start运行，就会报错：
./node_modules/react-router/index.js
Module not found: Can't resolve 'history' in 'E:\workspace\xiaosuibi\kite-admin-v2\node_modules\react-router'；
谢谢作者大神

**Comment by maoxiaoquan** [comment]
react-router  6.0.0-alpha.4 目前用的是alpha版本，你可能没装上，再用cnpm装下看看，我去看看官方有没有发稳定版本，再更新下，
感谢反馈

**Comment by wangwenyu0805** [comment]
> react-router 6.0.0-alpha.4 目前用的是alpha版本，你可能没装上，再用cnpm装下看看，我去看看官方有没有发稳定版本，再更新下，
> 感谢反馈

我用了npm，cnpm，yarn好像都有问题

**Comment by maoxiaoquan** [comment]
> > react-router 6.0.0-alpha.4 目前用的是alpha版本，你可能没装上，再用cnpm装下看看，我去看看官方有没有发稳定版本，再更新下，
> > 感谢反馈
> 
> 我用了npm，cnpm，yarn好像都有问题

ok,我拉远程的项目下来跑下

**Comment by wangwenyu0805** [comment]
> > > react-router 6.0.0-alpha.4 目前用的是alpha版本，你可能没装上，再用cnpm装下看看，我去看看官方有没有发稳定版本，再更新下，
> > > 感谢反馈
> > 
> > 
> > 我用了npm，cnpm，yarn好像都有问题
> 
> ok,我拉远程的项目下来跑下

作者大佬，你拉取后台管理项目运行有错误吗

**Comment by maoxiaoquan** [comment]
> 其他的步骤都做完了，前端也启动了，后台管理部分，我先npm install，再npm run start运行，就会报错：
> ./node_modules/react-router/index.js
> Module not found: Can't resolve 'history' in 'E:\workspace\xiaosuibi\kite-admin-v2\node_modules\react-router'；
> 谢谢作者大神

"react-router": "^6.0.0-beta.0",
"react-router-dom": "^6.0.0-beta.0",
已经定位到问题，你拉最新的代码下来跑就可以，我更新了react-router包

**Comment by wangwenyu0805** [comment]
> > 其他的步骤都做完了，前端也启动了，后台管理部分，我先npm install，再npm run start运行，就会报错：
> > ./node_modules/react-router/index.js
> > Module not found: Can't resolve 'history' in 'E:\workspace\xiaosuibi\kite-admin-v2\node_modules\react-router'；
> > 谢谢作者大神
> 
> "react-router": "^6.0.0-beta.0",
> "react-router-dom": "^6.0.0-beta.0",
> 已经定位到问题，你拉最新的代码下来跑就可以，我更新了react-router包

刚试了下，成功启动运行了，谢谢作者，3Q

**Comment by maoxiaoquan** [comment]
ok
